### ISSUE TITLE
add upsertUser mutation

### ISSUE THREAD

**Issue by HankC138** [goinvo/staffplan_redux#125]
Add a GraphQL mutation to add a new person to a company.

**Expectations**

- passing user parameters with no id will attempt to create a new user

- validation errors if it fails

- passing an id will attempt to update an existing user for the company

**Comment by HankC138** [comment]
This will likely need to include an upsertMembership mutation as well to alter/add a role to a user.

**Comment by fermion** [comment]
> This will likely need to include an upsertMembership mutation as well to alter/add a role to a user.

The membership will be created by upsertUser — it'll first upsert the user, then create the membership with the right role 👍🏻

**Comment by dreeves4321** [comment]
I think that's fine for v1. In the future, we'd want to be able to create a new person in-app. It would be annoying to be navigated away to create the person, then have to come back and edit their details (like their avatar). And then start assigning them. Also, as an aside, we'll need to consider someday allowing for non-user people. We sometimes have future employees or interns that we want to plan, but they can't have an account yet because they aren't actually employees yet. Maybe there's some other solution for that.
