### ISSUE TITLE
Add FTE values and optional hours field on projects

### ISSUE THREAD

**Issue by MyStarrySpace** [goinvo/staffplan_redux#155]

**Comment by fermion** [comment]
@MyStarrySpace would you mind filling in some details here? What data type do you propose and why?

**Comment by HankC138** [comment]
@fermion 
FTE shoud just be an integer or it may be called a float if it's a 1.0 to 1.5 to 2.0 etc, and hours should also just be an integer.

 The way they want projects to look there's FTE and hours fields but because they aren't hard fast rules they can't just be populated by some reverse math from the total cost of a project. It's my opinion that FTE should be stored in the backend with a minimum required value of one. Both of these values are part of the ability to edit a project and as it currently stands the values cannot be edited properly because they only exist to help calculate the total cost of a project when it's initially created.
