### ISSUE TITLE
New User Mgt: error on adding new user

### ISSUE THREAD

**Issue by jsonin** [goinvo/staffplan_redux#336]
<img width="598" alt="image" src="https://github.com/user-attachments/assets/09db343d-abaf-4998-8eeb-0409a329e0bd">

this happened after I just authenticated again...

**Comment by fermion** [comment]
What browser are you using? Are you using a single tab? Is it intermittent or does it happen every time you try to add someone?

**Comment by fermion** [comment]
@jsonin do you remember what you had just done previously, if anything?

**Comment by fermion** [comment]
I _think_ this and other issues we've had with forms are related to disabling Turbo on forms in the app. I'm going to spend some time refactoring these so that they use Turbo properly which _should_ fix the issue.

**Comment by fermion** [comment]
I saw this occur locally while clicking around working through a rewrite of the Rails form UIs to use turbo streams. What I did was:

* created new client A _in the Rails UI, not React_ (there are no links/buttons to this section, but it's there so I'm changing it)
* clicked "new client" button to bring up the form
* tried to create client B
* observed the 422 error page

Checking the network traffic between my browser and the server, I observed things in the following order:

* created client A
* a GET to /sign_out signing me out
* a load of /sign_in after being redirected
* CSRF error when trying to create client B

What I think is happening here is that Chrome is following the GET link to sign_out. This is on me, since I've wired up the sign_out link to be a regular link, not a form whose method is `DELETE` like I would have normally done.

I can't say why Chrome chooses to follow this when it does, but when it does it would have the effect of causing a mismatch of the CSRF token since it signs you out of the app. On top of the turbo stream changes, I'll be updating the Rails UI a bit to look a little more like the React one _and_ will make the sign out buttons part of a form so that Chrome won't try to follow them to preload the content.

**Comment by jsonin** [comment]
> @jsonin do you remember what you had just done previously, if anything?

I cant remember. 
I will make a better habit of including that for any next bug.

**Comment by fermion** [comment]
> > @jsonin do you remember what you had just done previously, if anything?
> 
> I cant remember. I will make a better habit of including that for any next bug.

@jsonin all good. I just had a hunch that this might be connected to a certain set of actions being taken 🤷🏻

**Comment by fermion** [comment]
Should hopefully be fixed with https://github.com/goinvo/staffplan_redux/pull/349 🤞🏻
